name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]
        poetry-version: [1.8.2]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install poetry==${{ matrix.poetry-version }}
        echo "$GITHUB_WORKSPACE/env/bin" >> $GITHUB_PATH

    - name: View poetry --help
      run: poetry --help

    - name: Install project dependencies
      run: poetry install

    - name: Set environment variables
      run: |
        echo "DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]" >> $GITHUB_ENV

    - name: Test
      run: poetry run python manage.py test
